# Necessary libraries

````python
conda install ipython
conda install jupyter
pip install sklearn
pip install scikit-image
pip install imutils
pip install opencv-contrib-python
pip install opencv-python
conda install keras
conda install tensorflow
pip install scikit-learn
pip install mlxtend
```` 
   




In [1]:
#load data
import numpy as np
import matplotlib.pyplot       as plt

data = np.loadtxt('datosML/diabetes.data',delimiter=',')
data


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [3]:
X = data[:,:8]
y = data[:,8].astype(int)

print("[INFO]\nX: %s\nY: %s"%(X.shape,y.shape))

[INFO]
X: (768, 8)
Y: (768,)


In [4]:
#multilayer feedforward
from keras.models import Sequential
from keras.layers import Dense

In [5]:
num_classes = 2
hl1 = 12
hl2 = 8
hl3 = 1



model = Sequential()
model.add(Dense(hl1, input_dim=8, activation='relu'))
model.add(Dense(hl2, activation='relu'))
model.add(Dense(hl3, activation='sigmoid'))  
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [8]:
!pip install sklearn


In [10]:
!pip install scikit-learn

     ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
     - -------------------------------------- 0.4/8.3 MB 7.4 MB/s eta 0:00:02
     ---- ----------------------------------- 0.9/8.3 MB 9.9 MB/s eta 0:00:01
     ------- -------------------------------- 1.5/8.3 MB 11.0 MB/s eta 0:00:01
     ---------- ----------------------------- 2.2/8.3 MB 11.9 MB/s eta 0:00:01
     -------------- ------------------------- 3.0/8.3 MB 12.8 MB/s eta 0:00:01
     ------------------- -------------------- 4.0/8.3 MB 14.1 MB/s eta 0:00:01
     ----------------------- ---------------- 5.0/8.3 MB 15.1 MB/s eta 0:00:01
     ----------------------------- ---------- 6.1/8.3 MB 16.2 MB/s eta 0:00:01
     ---------------------------------- ----- 7.1/8.3 MB 16.9 MB/s eta 0:00:01
     ---------------------------------------  8.3/8.3 MB 17.6 MB/s eta 0:00:01
     ---------------------------------------- 8.3/8.3 MB 16.1 MB/s eta 0:00:00
     ---------------------------------------- 0.0/298.0 kB ? e

In [11]:
#separar datos train test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
#'binary_crossentropy'

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
54/54 [==============================] - 2s 2ms/step - loss: 11.9921 - accuracy: 0.6127
Epoch 2/100
54/54 [==============================] - 0s 2ms/step - loss: 3.4450 - accuracy: 0.5251
Epoch 3/100
54/54 [==============================] - 0s 2ms/step - loss: 1.2644 - accuracy: 0.5847
Epoch 4/100
54/54 [==============================] - 0s 2ms/step - loss: 1.0287 - accuracy: 0.5791
Epoch 5/100
54/54 [==============================] - 0s 2ms/step - loss: 0.9650 - accuracy: 0.5791
Epoch 6/100
54/54 [==============================] - 0s 2ms/step - loss: 0.8944 - accuracy: 0.5661
Epoch 7/100
54/54 [==============================] - 0s 2ms/step - loss: 0.9021 - accuracy: 0.5736
Epoch 8/100
54/54 [==============================] - 0s 2ms/step - loss: 0.8290 - accuracy: 0.5866
Epoch 9/100
54/54 [==============================] - 0s 2ms/step - loss: 0.8279 - accuracy: 0.6313
Epoch 10/100
54/54 [==============================] - 0s 2ms/step - loss: 0.8146 - accuracy: 0.5829
Epoch 11

54/54 [==============================] - 0s 2ms/step - loss: 0.5659 - accuracy: 0.7225
Epoch 84/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5614 - accuracy: 0.7225
Epoch 85/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5451 - accuracy: 0.7467
Epoch 86/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5965 - accuracy: 0.7076
Epoch 87/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5714 - accuracy: 0.7281
Epoch 88/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5718 - accuracy: 0.7114
Epoch 89/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5575 - accuracy: 0.7169
Epoch 90/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5961 - accuracy: 0.7076
Epoch 91/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5662 - accuracy: 0.7039
Epoch 92/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5517 - accuracy: 0.7374
Epoch 93/100


In [16]:
predictions = model.predict(X_test)
predictions[0]

8/8 [==============================] - 0s 3ms/step


array([0.5474023], dtype=float32)

In [17]:
predictions[:10]

array([[0.5474023 ],
       [0.1825961 ],
       [0.7648486 ],
       [0.6166362 ],
       [0.20401846],
       [0.53092694],
       [0.4994509 ],
       [0.33865374],
       [0.5577194 ],
       [0.26844573]], dtype=float32)

In [18]:
# round predictions 
rounded = [round(x[0].astype(int)) for x in predictions]
rounded[0]

0

In [19]:
print("etiqueta 10 primeros datos de prueba:  ",y_test[:10],\
      "\nprediccion 10 primeros datos de prueba:",rounded[:10])

etiqueta 10 primeros datos de prueba:   [1 0 1 1 0 1 0 0 1 0] 
prediccion 10 primeros datos de prueba: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [20]:
_, accuracy = model.evaluate(X_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))


8/8 [==============================] - 0s 2ms/step - loss: 0.5256 - accuracy: 0.7446
Accuracy: 74.46


In [21]:
# summarize the first 5 cases
for i in range(5):
        print('%s => %d (expected %d)' % (X_test[i].tolist(), rounded[i], y_test[i]))

[3.0, 121.0, 52.0, 0.0, 0.0, 36.0, 0.127, 25.0] => 0 (expected 1)
[2.0, 95.0, 54.0, 14.0, 88.0, 26.1, 0.748, 22.0] => 0 (expected 0)
[7.0, 194.0, 68.0, 28.0, 0.0, 35.9, 0.745, 41.0] => 0 (expected 1)
[9.0, 145.0, 80.0, 46.0, 130.0, 37.9, 0.637, 40.0] => 0 (expected 1)
[2.0, 157.0, 74.0, 35.0, 440.0, 39.4, 0.134, 30.0] => 0 (expected 0)
