In [1]:
#load data
import numpy as np
import matplotlib.pyplot       as plt

data = np.loadtxt('datosML/diabetes.data',delimiter=',')
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [2]:
X = data[:,:8]
y = data[:,8].astype(int)

print("[INFO]\nX: %s\nY: %s"%(X.shape,y.shape))

[INFO]
X: (768, 8)
Y: (768,)


In [2]:
#multilayer feedforward
from keras.models import Sequential
from keras.layers import Dense

ModuleNotFoundError: No module named 'keras'

In [9]:
num_classes = 2
hl1 = 12
hl2 = 8
hl3 = 1



model = Sequential()
model.add(Dense(hl1, input_dim=8, activation='relu'))
model.add(Dense(hl2, activation='relu'))
model.add(Dense(hl3, activation='sigmoid'))  
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [10]:
#separar datos train test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
#'binary_crossentropy'

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
54/54 [==============================] - 0s 3ms/step - loss: 9.9068 - accuracy: 0.4451
Epoch 2/100
54/54 [==============================] - 0s 5ms/step - loss: 5.3543 - accuracy: 0.4209
Epoch 3/100
54/54 [==============================] - 0s 4ms/step - loss: 3.6021 - accuracy: 0.4227
Epoch 4/100
54/54 [==============================] - 0s 3ms/step - loss: 2.1654 - accuracy: 0.4358
Epoch 5/100
54/54 [==============================] - 0s 3ms/step - loss: 1.6115 - accuracy: 0.4711
Epoch 6/100
54/54 [==============================] - 0s 3ms/step - loss: 1.3357 - accuracy: 0.5028
Epoch 7/100
54/54 [==============================] - 0s 3ms/step - loss: 1.1612 - accuracy: 0.5177
Epoch 8/100
54/54 [==============================] - 0s 3ms/step - loss: 0.9267 - accuracy: 0.5363
Epoch 9/100
54/54 [==============================] - 0s 3ms/step - loss: 0.8627 - accuracy: 0.5829
Epoch 10/100
54/54 [==============================] - 0s 3ms/step - loss: 0.8233 - accuracy: 0.5959
Epoch 11/

54/54 [==============================] - 0s 5ms/step - loss: 0.5322 - accuracy: 0.7412
Epoch 84/100
54/54 [==============================] - 0s 4ms/step - loss: 0.5336 - accuracy: 0.7561
Epoch 85/100
54/54 [==============================] - 0s 4ms/step - loss: 0.5355 - accuracy: 0.7281
Epoch 86/100
54/54 [==============================] - 0s 3ms/step - loss: 0.5430 - accuracy: 0.7430
Epoch 87/100
54/54 [==============================] - 0s 4ms/step - loss: 0.5264 - accuracy: 0.7561
Epoch 88/100
54/54 [==============================] - 0s 4ms/step - loss: 0.5354 - accuracy: 0.7635
Epoch 89/100
54/54 [==============================] - 0s 4ms/step - loss: 0.5074 - accuracy: 0.7486
Epoch 90/100
54/54 [==============================] - 0s 4ms/step - loss: 0.5344 - accuracy: 0.7523
Epoch 91/100
54/54 [==============================] - 0s 5ms/step - loss: 0.5507 - accuracy: 0.7542
Epoch 92/100
54/54 [==============================] - 0s 6ms/step - loss: 0.5384 - accuracy: 0.7523
Epoch 93/100


In [12]:
predictions = model.predict(X_test)
predictions[0]

array([0.8525374], dtype=float32)

In [9]:
predictions[:10]

array([[0.22143352],
       [0.15440696],
       [0.5952276 ],
       [0.28859764],
       [0.58035755],
       [0.55076915],
       [0.22587582],
       [0.22263277],
       [0.58402395],
       [0.11575475]], dtype=float32)

In [13]:
# round predictions 
rounded = [round(x[0].astype(int)) for x in predictions]
rounded[0]

0

In [14]:
print("etiqueta 10 primeros datos de prueba:  ",y_test[:10],\
      "\nprediccion 10 primeros datos de prueba:",rounded[:10])

etiqueta 10 primeros datos de prueba:   [1 0 1 0 1 1 0 0 0 0] 
prediccion 10 primeros datos de prueba: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [15]:
_, accuracy = model.evaluate(X_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))


8/8 [==============================] - 0s 3ms/step - loss: 0.5741 - accuracy: 0.7273
Accuracy: 72.73


In [16]:
# summarize the first 5 cases
for i in range(5):
        print('%s => %d (expected %d)' % (X_test[i].tolist(), rounded[i], y_test[i]))

[0.0, 126.0, 86.0, 27.0, 120.0, 27.4, 0.515, 21.0] => 0 (expected 0)
[1.0, 103.0, 80.0, 11.0, 82.0, 19.4, 0.491, 22.0] => 0 (expected 0)
[3.0, 130.0, 64.0, 0.0, 0.0, 23.1, 0.314, 22.0] => 0 (expected 0)
[2.0, 122.0, 70.0, 27.0, 0.0, 36.8, 0.34, 27.0] => 0 (expected 0)
[7.0, 178.0, 84.0, 0.0, 0.0, 39.9, 0.331, 41.0] => 0 (expected 1)
